remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: bhg995
description: IT

defaults:
  - scope:
      path: "_appsec"
    values:
      layout: "default"
      permalink: "/appsec/:title/"
  - scope:
      path: "_confman"
    values:
      layout: "default"
      permalink: "/confman/:title/"
  - scope:
      path: "_linux"
    values:
      layout: "default"
      permalink: "/linux/:title/"

collections:
  appsec:
    output: true
  confman:
    output: true
  linux:
    output: true
