remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: IT
description: Reports about Linux machines and more

collections:
  appsec:
  output: true
  permalink: /_appsec/:title/

